name: zooper_table
description: "A highly versatile and dynamic table widget"
version: 1.0.0
homepage: https://zooper.dev

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1

  reorderables: ^0.6.0

  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
